<?=header("Content-Type: text/xml;charset=iso-8859-1"); '<?xml version="1.0" encoding="UTF-8"?>' ?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">


    <url>
        <loc>https://yescolleges.com/</loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>https://yescolleges.com/student-account-register</loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>https://yescolleges.com/info</loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>https://yescolleges.com/course-search</loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>https://yescolleges.com/search</loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>https://yescolleges.com/career</loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>https://yescolleges.com/blog/</loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>https://yescolleges.com/courses-category</loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>https://yescolleges.com/course-search?course=LLB</loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>
            https://yescolleges.com/course-search?course=airport-management
        </loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>https://yescolleges.com/course-search?course=BBM</loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>
            https://yescolleges.com/course-search?course=avation
        </loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>https://yescolleges.com/course-search?course=llb</loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>https://yescolleges.com/course-search?course=BBA</loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>https://yescolleges.com/course-search?course=MBA</loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>
            https://yescolleges.com/course-search?course=agriculture
        </loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>
            https://yescolleges.com/course-search?course=health-care
        </loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>
            https://yescolleges.com/course-search?course=international-business
        </loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>
            https://yescolleges.com/course-search?course=B.tech-computer-science
        </loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>
            https://yescolleges.com/course-search?course=B.tech-electronics-and-communication
        </loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>
            https://yescolleges.com/course-search?course=B.tech-mechanical-engineering
        </loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>
            https://yescolleges.com/course-search?course=B.tech-civil-engineering
        </loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>
            https://yescolleges.com/course-search?course=B.tech-electrical-engineering
        </loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>
            https://yescolleges.com/course-search?course=B.tech-aernotical-engineering
        </loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>
            https://yescolleges.com/course-search?course=M.tech-structural-engineering
        </loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>
            https://yescolleges.com/course-search?course=M.tech-mechanical-engineering
        </loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>
            https://yescolleges.com/course-search?course=M.tech-civil-engineering
        </loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>
            https://yescolleges.com/course-search?course=M.tech-soil-and-water-engineering
        </loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>
            https://yescolleges.com/course-search?course=mbbs-allopathy
        </loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>https://yescolleges.com/course-search?course=bams</loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>
            https://yescolleges.com/course-search?course=md-ortho
        </loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>
            https://yescolleges.com/course-search?course=md-anaesthesiloigy
        </loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>
            https://yescolleges.com/course-search?course=md-paediatrics
        </loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>
            https://yescolleges.com/course-search?course=md-homeopathy
        </loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>
            https://yescolleges.com/course-search?course=ms-anatomy
        </loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>
            https://yescolleges.com/course-search?course=ms-ent
        </loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>
            https://yescolleges.com/course-search?course=ms-ophthalmology
        </loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>
            https://yescolleges.com/course-search?course=ms-general-surgery
        </loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>https://yescolleges.com/course-search?course=bca</loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>
            https://yescolleges.com/course-search?course=bca-llb-hons
        </loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>
            https://yescolleges.com/course-search?course=optometry
        </loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>
            https://yescolleges.com/course-search?course=radio-therapy
        </loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>
            https://yescolleges.com/course-search?course=imaging-tech
        </loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>
            https://yescolleges.com/course-search?course=cardioc-tech
        </loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>
            https://yescolleges.com/course-search?course=anesthesia-tech
        </loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>https://yescolleges.com/allcolleges?page=1</loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>https://yescolleges.com/top-colleges</loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>https://yescolleges.com/college-reviews</loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>
            https://yescolleges.com/course-content-section?page=1
        </loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>https://yescolleges.com/online-admission</loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>https://yescolleges.com/expert-guidance</loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>https://yescolleges.com/top-reviews</loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>https://yescolleges.com/secure-payment</loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>https://yescolleges.com/customer-support</loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>https://yescolleges.com/not-available</loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>https://yescolleges.com/about</loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>https://yescolleges.com/vision-mission</loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>https://yescolleges.com/contact</loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>https://yescolleges.com/advertise-with-us</loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>https://yescolleges.com/faq</loc>
        <changefreq>weekly</changefreq>
    </url>

    <url>
        <loc>
            https://yescolleges.com/category-search-result/Agriculture
        </loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>
            https://yescolleges.com/category-search-result/Arts+and+Science
        </loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>
            https://yescolleges.com/category-search-result/Aviation
        </loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>
            https://yescolleges.com/category-search-result/Commerce
        </loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>
            https://yescolleges.com/category-search-result/Computer+Application
        </loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>
            https://yescolleges.com/category-search-result/Dental
        </loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>
            https://yescolleges.com/category-search-result/Design
        </loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>
            https://yescolleges.com/category-search-result/Veterinary+Science
        </loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>
            https://yescolleges.com/category-search-result/Veterinary+science
        </loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>
            https://yescolleges.com/category-search-result/Engineering
        </loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>
            https://yescolleges.com/category-search-result/Hotel+Management
        </loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>https://yescolleges.com/category-search-result/Law</loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>
            https://yescolleges.com/category-search-result/Management
        </loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>
            https://yescolleges.com/category-search-result/Mass+communication
        </loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>
            https://yescolleges.com/category-search-result/Medical
        </loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>
            https://yescolleges.com/category-search-result/Paramedical
        </loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>
            https://yescolleges.com/category-search-result/Pharmacy
        </loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>https://yescolleges.com/college/al-ameen-college</loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>
            https://yescolleges.com/college/adi-sankara-institute-of-engineering-and-technology
        </loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>
            https://yescolleges.com/college/rajagiri-school-of-engineering-and-technology
        </loc>
        <changefreq>weekly</changefreq>
    </url>

    <?php foreach($course as $url=>$value) {
        $value['name']=str_replace(' ','+',$value['name']);
        $value['catname']=str_replace(' ','+',$value['catname']);
        ?>

        <url>
            <loc><?= base_url().'course-individual-section/'.$value['catname'].'/'.$value['name'];?></loc>
            <priority>0.5</priority>
        </url>
    <?php } ?>


    <?php foreach($career as $url=>$value) {
        $value['name']=str_replace(' ','+',$value['name']);
        $value['category']=str_replace(' ','+',$value['category']);
        ?>

        <url>
            <loc><?= base_url().'career-individual-section/'.$value['category'].'/'.$value['name'];?></loc>
            <priority>0.5</priority>
        </url>
    <?php } ?>


    <?php foreach($seos as $url=>$value) { ?>
        <url>
            <loc><?= base_url().'college/'.$value['slug'] ?></loc>
            <priority>0.5</priority>
        </url>
    <?php } ?>

</urlset>